// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKdZxJPJXuUhXiahUEUT97bRIR0zol4fM',
    appId: '1:1073046051180:web:cdc1fff2a0243cde8f3b49',
    messagingSenderId: '1073046051180',
    projectId: 'bagtrip-7d2d8',
    authDomain: 'bagtrip-7d2d8.firebaseapp.com',
    storageBucket: 'bagtrip-7d2d8.firebasestorage.app',
    measurementId: 'G-SDDRN7T2V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAan5YoU-oASJ83q72hQIdPcShAodyeDPc',
    appId: '1:1073046051180:android:4f76589b84752cea8f3b49',
    messagingSenderId: '1073046051180',
    projectId: 'bagtrip-7d2d8',
    storageBucket: 'bagtrip-7d2d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOrIrl-wG7kacihBX74hBlneAPEs5Cwbg',
    appId: '1:1073046051180:ios:50920b37f76785558f3b49',
    messagingSenderId: '1073046051180',
    projectId: 'bagtrip-7d2d8',
    storageBucket: 'bagtrip-7d2d8.firebasestorage.app',
    iosBundleId: 'com.example.bagtrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOrIrl-wG7kacihBX74hBlneAPEs5Cwbg',
    appId: '1:1073046051180:ios:50920b37f76785558f3b49',
    messagingSenderId: '1073046051180',
    projectId: 'bagtrip-7d2d8',
    storageBucket: 'bagtrip-7d2d8.firebasestorage.app',
    iosBundleId: 'com.example.bagtrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKdZxJPJXuUhXiahUEUT97bRIR0zol4fM',
    appId: '1:1073046051180:web:263c7495222972f78f3b49',
    messagingSenderId: '1073046051180',
    projectId: 'bagtrip-7d2d8',
    authDomain: 'bagtrip-7d2d8.firebaseapp.com',
    storageBucket: 'bagtrip-7d2d8.firebasestorage.app',
    measurementId: 'G-RC52QQCNJZ',
  );
}
