FROM ghcr.io/cirruslabs/flutter:stable

WORKDIR /app

COPY . .

RUN flutter config --enable-web
RUN flutter pub get
RUN flutter gen-l10n

EXPOSE 5000

CMD ["flutter", "run", "-d", "web-server", "--web-hostname", "0.0.0.0", "--web-port", "5000"]
