#!/bin/bash
# Run flutter tests with coverage, filter out generated/boot code, enforce a threshold.
# The filtered lcov.info is what SonarQube should ingest.

set -e

# Threshold reflects the current baseline after filtering out generated/boot code.
# Bump this as each refactor phase lands more tests (target: 80%).
COVERAGE_THRESHOLD=${COVERAGE_THRESHOLD:-75}

cd "$(dirname "$0")"

echo "Running Flutter tests with coverage..."
flutter test --coverage

RAW_LCOV=coverage/lcov.info
if [ ! -f "$RAW_LCOV" ]; then
  echo "FAIL: $RAW_LCOV not produced"
  exit 1
fi

if ! command -v lcov &> /dev/null; then
  echo "lcov not installed — cannot filter or enforce threshold."
  echo "Install with: brew install lcov"
  exit 0
fi

# Patterns excluded from coverage accounting. Justification:
# - *.g.dart / *.freezed.dart: auto-generated, no behavior to test.
# - lib/l10n/app_localizations*.dart: auto-generated from ARB.
# - lib/gen/**: flutter_gen output (colors, fonts, assets).
# - lib/firebase_options.dart: auto-generated by flutterfire.
# - lib/main.dart: app bootstrap, exercised by E2E only.
# - lib/config/service_locator.dart: DI wiring, exercised by E2E.
# - lib/navigation/route_definitions*.dart + app_router + app_shell + page_transitions:
#     routing glue, exercised by E2E.
# - lib/pages/payment/**: Stripe redirect pages, tested end-to-end in staging.
EXCLUDE_PATTERNS=(
  'lib/l10n/app_localizations*.dart'
  'lib/gen/*'
  'lib/firebase_options.dart'
  'lib/main.dart'
  'lib/config/service_locator.dart'
  'lib/navigation/route_definitions.dart'
  'lib/navigation/route_definitions.g.dart'
  'lib/navigation/app_router.dart'
  'lib/navigation/app_shell.dart'
  'lib/navigation/page_transitions.dart'
  'lib/pages/payment/*'
  '*.g.dart'
  '*.freezed.dart'
)

FILTERED_LCOV=coverage/lcov.info
TMP_LCOV=coverage/lcov.raw.info
cp "$RAW_LCOV" "$TMP_LCOV"

lcov --remove "$TMP_LCOV" "${EXCLUDE_PATTERNS[@]}" \
  --output-file "$FILTERED_LCOV" \
  --ignore-errors unused,unused >/dev/null 2>&1

rm -f "$TMP_LCOV"

echo "Coverage report (post-filter) at: $FILTERED_LCOV"

COVERAGE=$(lcov --summary "$FILTERED_LCOV" 2>&1 | grep 'lines' | sed 's/.*: *\([0-9.]*\)%.*/\1/')
echo "Line coverage: ${COVERAGE}%"

if [ "$(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l)" -eq 1 ]; then
  echo "FAIL: Coverage ${COVERAGE}% is below threshold ${COVERAGE_THRESHOLD}%"
  exit 1
fi
echo "PASS: Coverage ${COVERAGE}% meets threshold ${COVERAGE_THRESHOLD}%"
